language: node_js

node_js:
  - "0.11"
  - "0.10"

branches:
  only:
    - master

before_script:
  - npm install istanbul
  - npm install coveralls
  - npm install mocha-lcov-reporter

after_script:
  - NODE_ENV=test npm run coverall 

